version: '3'

services:
  nginx:
    hostname: wp-host-nginx
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/${HOST_NAME}:delegated # project folder
      - ./docker/etc/nginx/local.conf:/etc/nginx/templates/default.conf.template
      - ./docker/var/log/nginx:/var/log/nginx
    ports: # override
      - ${HOST_PORT}:80
    environment:
      TZ : ${HOST_TZ}
      NGINX_HOST : ${HOST_NAME}
    networks:
      - wp-host-bridge

  php:
    volumes:
      - ./docker/etc/php/local.ini:/etc/php/7.4/fpm/conf.d/project.ini
